apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
        - name: doctor
          image: iliassanati/doctor
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ehealthApp
            - name: GEOCODER_PROVIDER
              value: mapquest
            - name: GEOCODER_API_KEY
              value: 'XvhAoG5JhR5wJ3TGEOkuDjoufdK2bo51'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: JWT_KEY_ADMIN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-admin
                  key: JWT_KEY_ADMIN

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-srv
spec:
  selector:
    app: doctor
  ports:
    - name: doctor
      protocol: TCP
      port: 3000
      targetPort: 3000
